"""
reviewer.py
-----------
CodeSentinel — Core review logic using LangGraph.

Graph Nodes:
  fetch_pr_files     → load PR diff from GitHub API
  retrieve_rules     → RAG: query Pinecone for relevant style rules per file
  review_code        → LangChain chain: CoT prompt | Gemini | JsonOutputParser
  format_comment     → build Markdown comment from structured review output
  post_comment       → post comment to PR via GitHub API
  no_files_to_review → early exit if no reviewable files

Edges:
  fetch_pr_files
    → no_files_to_review  (if nothing reviewable)
    → retrieve_rules      (otherwise)

  retrieve_rules → review_code → format_comment → post_comment
    → retrieve_rules  (loop: more files remain)
    → END             (all files done)
"""

import os
import sys
import logging
from typing import List, Optional, TypedDict

from github import Github, Auth
from pydantic import BaseModel, Field

from langchain_pinecone import PineconeVectorStore
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser

from langgraph.graph import StateGraph, END


# ── CONFIG ────────────────────────────────────────────────────────────────────

INDEX_NAME            = os.environ.get("PINECONE_INDEX_NAME", "code-sentinel-index")
GEMINI_MODEL          = "gemini-2.5-flash"
EMBED_MODEL           = "google/embeddinggemma-300m"
TOP_K_RULES           = 4
REVIEWABLE_EXTENSIONS = (".py", ".js", ".ts", ".java")


# ── OUTPUT SCHEMA ─────────────────────────────────────────────────────────────
#
# HOW THIS WORKS (important to understand):
#
#   1. We define the expected output shape as a Pydantic model (ReviewOutput).
#   2. JsonOutputParser(pydantic_object=ReviewOutput) reads this model
#      and generates a `format_instructions` string automatically —
#      a human-readable description of the required JSON fields.
#   3. We inject {format_instructions} into the prompt via `partial_variables`.
#   4. This means we NEVER manually write JSON schema in the prompt.
#      The parser owns the schema definition. The prompt just says
#      "respond according to {format_instructions}."
#   5. The parser then validates and parses the LLM's response back
#      into a Python dict matching the schema.

class Issue(BaseModel):
    line_reference: str = Field(description="The exact problematic line or snippet from the diff")
    violation_type: str = Field(description="Category: Naming Convention | Security | Code Style | Other")
    explanation:    str = Field(description="Why this violates the style rule, referencing the rule text")
    suggestion:     str = Field(description="The corrected/refactored version of the line or block")

class ReviewOutput(BaseModel):
    summary: str         = Field(description="One sentence overall assessment of the PR changes")
    passed:  bool        = Field(description="True if zero violations found, False otherwise")
    issues:  List[Issue] = Field(description="All violations found. Must be an empty list if passed=true")


# ── GRAPH STATE ───────────────────────────────────────────────────────────────
#
# TypedDict defines the shared state that flows between every LangGraph node.
# Each node receives the full state and returns a dict with only the keys it updates.

class ReviewState(TypedDict):
    # Set once at the start
    pr_number:    int
    repo_name:    str
    github_token: str

    # Populated and updated during graph execution
    pr_files:         List[dict]      # [{"filename": ..., "patch": ..., "status": ...}]
    current_file_idx: int             # index of the file currently being processed
    style_rules:      str             # retrieved Pinecone chunks for the current file
    review_result:    Optional[dict]  # parsed LLM output for current file
    comment_body:     str             # formatted Markdown string for current file
    comments_posted:  int             # running total of posted comments


# ── SHARED RESOURCES ─────────────────────────────────────────────────────────
# Built once in main(), passed into nodes via closures.

def build_retriever():
    embeddings = HuggingFaceEmbeddings(
        model_name=EMBED_MODEL,
        model_kwargs={"device": "cpu"},
        encode_kwargs={"normalize_embeddings": True}
    )
    vector_store = PineconeVectorStore(
        index_name=INDEX_NAME,
        embedding=embeddings,
    )
    return vector_store.as_retriever(search_kwargs={"k": TOP_K_RULES})


def build_chain():
    llm = ChatGoogleGenerativeAI(
        model=GEMINI_MODEL,
        temperature=0.1,
        google_api_key=os.environ.get("GOOGLE_API_KEY"),
    )

    parser = JsonOutputParser(pydantic_object=ReviewOutput)

    # {format_instructions} is auto-generated by the parser from ReviewOutput.
    # It gets baked into the prompt at build time via partial_variables.
    # The LLM sees the schema requirements without us writing them twice.
    prompt = PromptTemplate(
        input_variables=["filename", "code_diff", "style_rules"],
        partial_variables={
            "format_instructions": parser.get_format_instructions()
        },
        template="""
You are CodeSentinel, a senior code reviewer AI. Your task is to review a code diff
against the provided style guide rules and identify any violations.

<thinking>
Step 1 — Understand what changed.
  File: {filename}
  Lines starting with '+' are NEW additions. Focus your review on these.
  Lines starting with '-' are deletions (ignore for violations).

  CODE DIFF:
  {code_diff}

Step 2 — Read the applicable style rules for this code.
  These were retrieved from the company style guide based on the diff content:

  STYLE RULES:
  {style_rules}

Step 3 — For each added line, check for violations:
  - Naming conventions (variables, functions, classes)
  - Hardcoded secrets, API keys, passwords, tokens
  - Issues mentioned in the rules

Step 4 — For each violation: quote the exact line, explain why it violates a rule,
  and write a corrected version.

Step 5 — If no violations exist, set passed=true and issues=[].
</thinking>

Now produce your final structured output.
{format_instructions}
"""
    )

    return prompt | llm | parser


# ── GRAPH NODES ───────────────────────────────────────────────────────────────

def fetch_pr_files(state: ReviewState) -> dict:
    """Node 1: Pull the list of changed files and their diffs from the GitHub PR."""
    logging.info("📂 Node: fetch_pr_files")

    auth = Auth.Token(state["github_token"])
    g = Github(auth=auth)
    repo = g.get_repo(state["repo_name"])
    pr   = repo.get_pull(state["pr_number"])

    files = [
        {"filename": f.filename, "patch": f.patch, "status": f.status}
        for f in pr.get_files()
        if f.filename.endswith(REVIEWABLE_EXTENSIONS) and f.patch
    ]

    logging.info(f"   Found {len(files)} reviewable file(s): {[f['filename'] for f in files]}")
    return {
        "pr_files":         files,
        "current_file_idx": 0,
        "comments_posted":  0,
    }


def retrieve_rules(state: ReviewState, retriever) -> dict:
    """Node 2: Semantic search — find style rules relevant to the current file's diff."""
    logging.info("📚 Node: retrieve_rules")

    idx   = state["current_file_idx"]
    patch = state["pr_files"][idx]["patch"]

    docs = retriever.invoke(patch)
    style_rules = (
        "\n\n---\n\n".join(doc.page_content for doc in docs)
        if docs else
        "No specific rules retrieved. Apply general best practices."
    )

    fname = state["pr_files"][idx]["filename"]
    logging.info(f"   {len(docs)} rule chunk(s) retrieved for '{fname}'")
    return {"style_rules": style_rules}


def review_code(state: ReviewState, chain) -> dict:
    """Node 3: Run the CoT chain — prompt | Gemini 2.5 Flash | JsonOutputParser."""
    logging.info("🧠 Node: review_code")

    idx  = state["current_file_idx"]
    file = state["pr_files"][idx]

    result = chain.invoke({
        "filename":    file["filename"],
        "code_diff":   file["patch"],
        "style_rules": state["style_rules"],
    })

    issue_count = len(result.get("issues", []))
    logging.info(f"   {'✅ Passed' if result.get('passed') else f'⚠️  {issue_count} issue(s) found'}")
    return {"review_result": result}


def format_comment(state: ReviewState) -> dict:
    """Node 4: Convert the parsed review dict into a clean, scannable Markdown comment."""
    logging.info("📝 Node: format_comment")

    idx = state["current_file_idx"]
    filename = state["pr_files"][idx]["filename"]
    review = state["review_result"]
    
    # Map extensions to markdown language identifiers
    ext_map = {".py": "python", ".js": "javascript", ".ts": "typescript", ".java": "java"}
    file_ext = os.path.splitext(filename)[1]
    lang = ext_map.get(file_ext, "")

    issues = review.get("issues", [])
    passed = review.get("passed", True)
    summary = review.get("summary", "")

    # Header and Summary
    lines = [
        f"## 🤖 CodeSentinel | `{filename}`",
        f"> {summary}",
        "---"
    ]

    if passed or not issues:
        lines.append("### ✅ No issues found. Great job!")
    else:
        lines.append(f"### ⚠️ {len(issues)} Violation(s) Found")
        
        for i, issue in enumerate(issues, 1):
            violation = issue.get('violation_type', 'Style Issue')
            
            # Use a collapsible section for each issue
            lines += [
                f"<details open>",
                f"<summary><b>Issue #{i}: {violation}</b></summary>",
                "",
                "| Property | Details |",
                "| :--- | :--- |",
                f"| **Type** | {violation} |",
                f"| **Context** | `{filename}` |",
                "",
                "#### 💬 Rationale",
                issue.get('explanation', ''),
                "",
                "#### 📍 Current Code",
                f"```{lang}",
                issue.get("line_reference", ""),
                "```",
                "",
                "#### ✅ Suggested Fix",
                f"```{lang}",
                issue.get("suggestion", ""),
                "```",
                "</details>",
                ""
            ]

    return {"comment_body": "\n".join(lines)}


def post_comment(state: ReviewState, github_token: str) -> dict:
    """Node 5: Post the formatted comment on the PR and advance to the next file."""
    logging.info("💬 Node: post_comment")

    auth = Auth.Token(state["github_token"])
    g = Github(auth=auth)
    repo = g.get_repo(state["repo_name"])
    pr   = repo.get_pull(state["pr_number"])

    pr.create_issue_comment(state["comment_body"])

    fname = state["pr_files"][state["current_file_idx"]]["filename"]
    logging.info(f"   Comment posted for '{fname}'")

    return {
        "comments_posted":  state["comments_posted"] + 1,
        "current_file_idx": state["current_file_idx"] + 1,
    }


def no_files_to_review(state: ReviewState) -> dict:
    """Node: Early exit when no reviewable files exist in the PR."""
    logging.info("ℹ️  Node: no_files_to_review — no .py/.js/.ts/.java files changed.")
    return {}


# ── CONDITIONAL EDGE FUNCTIONS ────────────────────────────────────────────────

def route_after_fetch(state: ReviewState) -> str:
    """Decide: are there files to review, or should we exit early?"""
    return "no_files_to_review" if not state["pr_files"] else "retrieve_rules"


def route_after_post(state: ReviewState) -> str:
    """Decide: are there more files to review, or are we done?"""
    if state["current_file_idx"] < len(state["pr_files"]):
        return "retrieve_rules"
    return END


# ── BUILD THE GRAPH ───────────────────────────────────────────────────────────

def build_graph(retriever, chain, github_token: str):
    """Assemble and compile the LangGraph StateGraph."""

    # Wrap nodes needing shared resources in closures so they match (state) -> dict signature
    def _retrieve_rules(state): return retrieve_rules(state, retriever)
    def _review_code(state):    return review_code(state, chain)
    def _post_comment(state):   return post_comment(state, github_token)

    graph = StateGraph(ReviewState)

    # Register nodes
    graph.add_node("fetch_pr_files",     fetch_pr_files)
    graph.add_node("retrieve_rules",     _retrieve_rules)
    graph.add_node("review_code",        _review_code)
    graph.add_node("format_comment",     format_comment)
    graph.add_node("post_comment",       _post_comment)
    graph.add_node("no_files_to_review", no_files_to_review)

    # Entry point
    graph.set_entry_point("fetch_pr_files")

    # Edges
    graph.add_conditional_edges(
        "fetch_pr_files",
        route_after_fetch,
        {
            "retrieve_rules":     "retrieve_rules",
            "no_files_to_review": "no_files_to_review",
        }
    )
    graph.add_edge("retrieve_rules", "review_code")
    graph.add_edge("review_code",    "format_comment")
    graph.add_edge("format_comment", "post_comment")

    # Conditional loop: next file OR finish
    graph.add_conditional_edges(
        "post_comment",
        route_after_post,
        {
            "retrieve_rules": "retrieve_rules",
            END:              END,
        }
    )
    graph.add_edge("no_files_to_review", END)

    return graph.compile()


# ── MAIN ──────────────────────────────────────────────────────────────────────

def main():
    logging.basicConfig(level=logging.INFO, format='%(message)s')
    logging.info("🚀 CodeSentinel starting...\n")

    github_token = os.environ.get("GITHUB_TOKEN")
    repo_name    = os.environ.get("GITHUB_REPOSITORY")
    pr_number    = os.environ.get("PR_NUMBER")

    if not all([github_token, repo_name, pr_number]):
        logging.error("❌ Missing env vars: GITHUB_TOKEN, GITHUB_REPOSITORY, or PR_NUMBER")
        sys.exit(1)

    logging.info("🔌 Connecting to Pinecone...")
    retriever = build_retriever()

    logging.info("⛓️  Building review chain...")
    chain = build_chain()

    logging.info("🗺️  Compiling LangGraph...\n")
    app = build_graph(retriever, chain, github_token)

    final_state = app.invoke({
        "pr_number":      int(pr_number),
        "repo_name":      repo_name,
        "github_token":   github_token,
        "pr_files":         [],
        "current_file_idx": 0,
        "style_rules":      "",
        "review_result":    None,
        "comment_body":     "",
        "comments_posted":  0,
    })

    logging.info(f"\n✅ CodeSentinel done. Posted {final_state.get('comments_posted', 0)} review comment(s).")


if __name__ == "__main__":
    main()
